project:
  type: website
  output-dir: _site

website:
  title: "Sandbox"
  site-url: https://anjaliverma01.github.io/Sandbox/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts/index.qmd
        text: Blog
      - href: projects.qmd
        text: Projects
      - href: talks.qmd
        text: Talks
      - href: publications.qmd
        text: Publications
    right:
      - icon: github
        href: https://github.com/anjaliverma01

format:
  html:
    theme: cosmo
    css: styles.scss
    toc: false
